package com.blinkmap.mod;
import android.app.PendingIntent;import android.appwidget.AppWidgetManager;import android.appwidget.AppWidgetProvider;import android.content.Context;import android.content.Intent;import android.net.Uri;import android.widget.RemoteViews;import java.util.List;
public final class CompactFriendWidgetProvider extends AppWidgetProvider {
 private static final String ACTION="app.blinkmod.WIDGET_COMPACT_REFRESH";
 @Override public void onUpdate(Context c,AppWidgetManager m,int[] ids){for(int id:ids)update(c,m,id);}
 @Override public void onReceive(Context c,Intent i){super.onReceive(c,i);if(ACTION.equals(i.getAction())){int id=i.getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,-1);if(id>=0)update(c,AppWidgetManager.getInstance(c),id);}}
 static void update(Context c,AppWidgetManager manager,int widgetId){int layout=FriendWidgetProvider.id(c,"layout","blinkmod_friend_widget_compact");if(layout==0)return;RemoteViews v=new RemoteViews(c.getPackageName(),layout);android.content.SharedPreferences p=c.getSharedPreferences(FriendWidgetProvider.PREFS,0);long selected=p.getLong("widget_friend_"+widgetId,-1);MarkerStore.Marker marker=selected<0?null:MarkerStore.find(c,selected);if(marker==null){List<MarkerStore.Marker> all=MarkerStore.load(c);if(!all.isEmpty()){marker=all.get(0);p.edit().putLong("widget_friend_"+widgetId,marker.id).apply();}}
  int map=FriendWidgetProvider.id(c,"id","compact_map"),name=FriendWidgetProvider.id(c,"id","compact_name"),detail=FriendWidgetProvider.id(c,"id","compact_detail"),root=FriendWidgetProvider.id(c,"id","compact_root"),refresh=FriendWidgetProvider.id(c,"id","compact_refresh"),settings=FriendWidgetProvider.id(c,"id","compact_settings");v.setImageViewBitmap(map,FriendWidgetProvider.mapPreview(c,marker));
  if(marker==null){v.setTextViewText(name,"BlinkMod");v.setTextViewText(detail,"нет маркеров");}else{v.setTextViewText(name,marker.displayName());String d=MarkerStore.distance(marker.distance);if(p.getBoolean("widget_age_"+widgetId,true))d+=" · "+MarkerStore.age(marker.updatedAt);v.setTextViewText(detail,d);Intent open=new Intent(Intent.ACTION_VIEW,Uri.parse("blink:///map/marker/?id="+marker.id)).setPackage(c.getPackageName());v.setOnClickPendingIntent(root,PendingIntent.getActivity(c,widgetId,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));}
  Intent r=new Intent(c,CompactFriendWidgetProvider.class).setAction(ACTION).putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,widgetId);v.setOnClickPendingIntent(refresh,PendingIntent.getBroadcast(c,widgetId,r,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));Intent cfg=new Intent(c,FriendWidgetConfigActivity.class).putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,widgetId).putExtra("edit",true);v.setOnClickPendingIntent(settings,PendingIntent.getActivity(c,widgetId+100000,cfg,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));manager.updateAppWidget(widgetId,v);}
 @Override public void onDeleted(Context c,int[] ids){android.content.SharedPreferences.Editor e=c.getSharedPreferences(FriendWidgetProvider.PREFS,0).edit();for(int id:ids){e.remove("widget_friend_"+id);e.remove("widget_zoom_"+id);e.remove("widget_age_"+id);e.remove("widget_battery_"+id);e.remove("widget_speed_"+id);}e.apply();}
}
