package com.blinkmap.mod;

import android.app.Activity;
import android.appwidget.AppWidgetManager;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.graphics.Rect;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.PixelCopy;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Switch;
import android.widget.TextView;
import java.io.FileOutputStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.List;

public final class FriendWidgetConfigActivity extends Activity {
    private int widgetId=AppWidgetManager.INVALID_APPWIDGET_ID;
    private MarkerStore.Marker marker;private View mapView;private FrameLayout mapFrame;private double zoom=15.0;
    private Switch showAge,showBattery,showSpeed;private Handler handler=new Handler(Looper.getMainLooper());
    @Override protected void onCreate(Bundle b){super.onCreate(b);setResult(RESULT_CANCELED);widgetId=getIntent().getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,AppWidgetManager.INVALID_APPWIDGET_ID);long id=getSharedPreferences(FriendWidgetProvider.PREFS,0).getLong("widget_friend_"+widgetId,-1);marker=id<0?null:MarkerStore.find(this,id);if(getIntent().getBooleanExtra("edit",false)&&marker!=null)renderSettings();else renderChooser();}
    private void renderChooser(){destroyMap();LinearLayout root=base();TextView title=t("Друг на карте",30,Color.WHITE);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(title,new LinearLayout.LayoutParams(-1,dp(54)));root.addView(t("Выбери, кого показывать в виджете",15,Color.rgb(155,155,165)),new LinearLayout.LayoutParams(-1,dp(42)));ScrollView scroll=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);List<MarkerStore.Marker> markers=MarkerStore.load(this);if(markers.isEmpty()){TextView empty=t("Маркеры не найдены. Открой карту Blink, дождись друзей и попробуй снова.",16,Color.rgb(190,190,198));empty.setPadding(dp(16),dp(18),dp(16),dp(18));empty.setBackground(bg(Color.rgb(28,28,32),18));list.addView(empty);}else for(final MarkerStore.Marker m:markers){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(16),dp(10),dp(16),dp(10));row.setBackground(bg(Color.rgb(28,28,32),17));TextView name=t(m.displayName(),18,Color.WHITE);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);row.addView(name);row.addView(t(MarkerStore.distance(m.distance)+" · "+MarkerStore.age(m.updatedAt),14,Color.rgb(155,155,165)));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(76));rp.bottomMargin=dp(9);list.addView(row,rp);row.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){marker=m;getSharedPreferences(FriendWidgetProvider.PREFS,0).edit().putLong("widget_friend_"+widgetId,m.id).apply();renderSettings();}});}scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private void renderSettings(){destroyMap();SharedPreferences p=getSharedPreferences(FriendWidgetProvider.PREFS,0);zoom=Double.longBitsToDouble(p.getLong("widget_zoom_"+widgetId,Double.doubleToLongBits(15.0)));LinearLayout root=base();LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",38,Color.WHITE);back.setGravity(Gravity.CENTER);bar.addView(back,new LinearLayout.LayoutParams(dp(46),dp(52)));TextView title=t("Настройки виджета",24,Color.WHITE);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bar.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(bar);back.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){renderChooser();}});
        ScrollView scroll=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.addView(section("ПРЕДПРОСМОТР"));mapFrame=new FrameLayout(this);mapFrame.setBackground(bg(Color.rgb(34,34,39),22));body.addView(mapFrame,new LinearLayout.LayoutParams(-1,dp(210)));TextView pin=t("●",30,Color.rgb(132,78,255));pin.setGravity(Gravity.CENTER);mapFrame.addView(pin,new FrameLayout.LayoutParams(-1,-1));
        body.addView(section("МАСШТАБ КАРТЫ"));final LinearLayout scales=new LinearLayout(this);scales.setGravity(Gravity.CENTER);final Button district=chip("Район"),streets=chip("Улицы"),house=chip("Дом");scales.addView(district,new LinearLayout.LayoutParams(0,dp(48),1));scales.addView(streets,new LinearLayout.LayoutParams(0,dp(48),1));scales.addView(house,new LinearLayout.LayoutParams(0,dp(48),1));body.addView(scales);View.OnClickListener scaleClick=new View.OnClickListener(){@Override public void onClick(View v){zoom=v==district?13.0:v==house?17.0:15.0;paintScales(district,streets,house);centerMap();}};district.setOnClickListener(scaleClick);streets.setOnClickListener(scaleClick);house.setOnClickListener(scaleClick);paintScales(district,streets,house);
        body.addView(section("ИНФОРМАЦИЯ"));showAge=toggle(body,"Когда обновлялась",p.getBoolean("widget_age_"+widgetId,true));showBattery=toggle(body,"Заряд телефона друга",p.getBoolean("widget_battery_"+widgetId,true));showSpeed=toggle(body,"Скорость движения",p.getBoolean("widget_speed_"+widgetId,true));TextView hint=t("Карта рендерится родным движком Blink и сохраняется в виджет.",13,Color.rgb(135,135,145));hint.setPadding(dp(4),dp(16),dp(4),dp(12));body.addView(hint);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));Button save=chip("Сохранить");save.setTextSize(17);save.setTextColor(Color.WHITE);save.setBackground(bg(Color.rgb(126,76,255),18));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(56));sp.topMargin=dp(12);root.addView(save,sp);save.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){saveAndFinish();}});setContentView(root);startBlinkMap();}
    private void startBlinkMap(){if(marker==null||mapFrame==null)return;try{Class<?> cls=Class.forName("com.maps.sdk.MapView");Constructor<?> ctor=cls.getConstructor(android.content.Context.class);mapView=(View)ctor.newInstance(this);mapFrame.addView(mapView,0,new FrameLayout.LayoutParams(-1,-1));}catch(Throwable e){mapView=null;TextView msg=t("Не удалось запустить карту Blink",14,Color.rgb(180,180,190));msg.setGravity(Gravity.CENTER);mapFrame.addView(msg,0,new FrameLayout.LayoutParams(-1,-1));return;}safeCall("setCompassVisible",new Class[]{boolean.class},new Object[]{false});safeCall("setZoomButtonsVisible",new Class[]{boolean.class},new Object[]{false});safeCall("setCurrentLocationButtonVisible",new Class[]{boolean.class},new Object[]{false});safeCall("setScrollGesturesEnabled",new Class[]{boolean.class},new Object[]{false});safeCall("setZoomGesturesEnabled",new Class[]{boolean.class},new Object[]{false});safeCall("onResume",new Class[0],new Object[0]);handler.postDelayed(new Runnable(){@Override public void run(){centerMap();}},700);handler.postDelayed(new Runnable(){@Override public void run(){centerMap();}},1800);}
    private void centerMap(){if(mapView==null||marker==null)return;try{Class<?> latCls=Class.forName("com.maps.sdk.data.LatLon"),coordIface=Class.forName("com.maps.sdk.data.CameraOptions$Coordinates"),centerCls=Class.forName("com.maps.sdk.data.CameraOptions$Coordinates$Center"),insetsCls=Class.forName("com.maps.sdk.data.MapInsets"),optsCls=Class.forName("com.maps.sdk.data.CameraOptions"),reasonCls=Class.forName("com.maps.sdk.data.MapEvent$CameraMovingReason"),codeCls=Class.forName("com.maps.sdk.data.MapEvent$CameraMovingReason$Code"),animCls=Class.forName("com.maps.sdk.data.AnimationOptions"),fnCls=Class.forName("kotlin.jvm.functions.Function1");Object lat=latCls.getConstructor(double.class,double.class).newInstance(marker.latitude,marker.longitude);Object center=centerCls.getConstructor(latCls).newInstance(lat);Object opts=optsCls.getConstructor(coordIface,Double.class,Double.class,insetsCls,Double.class).newInstance(center,Double.valueOf(zoom),null,null,Double.valueOf(0));Object reason=codeCls.getField("INSTANCE").get(null);final Object unit=Class.forName("kotlin.Unit").getField("INSTANCE").get(null);Object callback=Proxy.newProxyInstance(fnCls.getClassLoader(),new Class[]{fnCls},(proxy,method,args)->unit);Object camera=mapView.getClass().getMethod("getCameraController").invoke(mapView);camera.getClass().getMethod("flyTo",optsCls,animCls,reasonCls,boolean.class,fnCls).invoke(camera,opts,null,reason,false,callback);}catch(Throwable ignored){}}
    private void saveAndFinish(){SharedPreferences.Editor e=getSharedPreferences(FriendWidgetProvider.PREFS,0).edit();e.putLong("widget_friend_"+widgetId,marker.id).putLong("widget_zoom_"+widgetId,Double.doubleToLongBits(zoom)).putBoolean("widget_age_"+widgetId,showAge.isChecked()).putBoolean("widget_battery_"+widgetId,showBattery.isChecked()).putBoolean("widget_speed_"+widgetId,showSpeed.isChecked()).apply();if(mapFrame==null||mapFrame.getWidth()<2){complete();return;}final int[] xy=new int[2];mapFrame.getLocationInWindow(xy);final Rect src=new Rect(xy[0],xy[1],xy[0]+mapFrame.getWidth(),xy[1]+mapFrame.getHeight());final Bitmap out=Bitmap.createBitmap(src.width(),src.height(),Bitmap.Config.ARGB_8888);try{PixelCopy.request(getWindow(),src,out,new PixelCopy.OnPixelCopyFinishedListener(){@Override public void onPixelCopyFinished(int result){if(result==PixelCopy.SUCCESS)try{FileOutputStream f=new FileOutputStream(FriendWidgetProvider.mapFile(FriendWidgetConfigActivity.this,marker.id));out.compress(Bitmap.CompressFormat.PNG,92,f);f.close();}catch(Throwable ignored){}complete();}},handler);}catch(Throwable t){complete();}}
    private void complete(){AppWidgetManager manager=AppWidgetManager.getInstance(this);android.appwidget.AppWidgetProviderInfo info=manager.getAppWidgetInfo(widgetId);if(info!=null&&info.provider!=null&&info.provider.getClassName().contains("CompactFriendWidgetProvider"))CompactFriendWidgetProvider.update(this,manager,widgetId);else FriendWidgetProvider.update(this,manager,widgetId);Intent result=new Intent().putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,widgetId);setResult(RESULT_OK,result);finish();}
    private Switch toggle(LinearLayout body,String label,boolean checked){Switch s=new Switch(this);s.setText(label);s.setTextSize(16);s.setTextColor(Color.WHITE);s.setGravity(Gravity.CENTER_VERTICAL);s.setChecked(checked);s.setPadding(dp(14),0,dp(10),0);s.setBackground(bg(Color.rgb(28,28,32),16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(58));lp.bottomMargin=dp(7);body.addView(s,lp);return s;}
    private void paintScales(Button a,Button b,Button c){Button[] all={a,b,c};for(Button x:all){boolean on=(x==a&&zoom==13)||(x==b&&zoom==15)||(x==c&&zoom==17);x.setTextColor(on?Color.WHITE:Color.rgb(175,175,185));x.setBackground(bg(on?Color.rgb(126,76,255):Color.rgb(28,28,32),16));}}
    private Button chip(String s){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextSize(15);return b;}
    private TextView section(String s){TextView v=t(s,12,Color.rgb(130,130,140));v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setPadding(dp(4),dp(18),0,dp(8));return v;}
    private LinearLayout base(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(18));r.setBackgroundColor(Color.rgb(10,10,12));return r;}
    private Object call(Object target,String name,Class[] types,Object[] args)throws Exception{return target.getClass().getMethod(name,types).invoke(target,args);}
    private void safeCall(String name,Class[] types,Object[] args){if(mapView!=null)try{call(mapView,name,types,args);}catch(Throwable ignored){}}
    private void destroyMap(){if(mapView!=null){try{call(mapView,"onPause",new Class[0],new Object[0]);call(mapView,"destroy",new Class[0],new Object[0]);}catch(Throwable ignored){}mapView=null;}}
    @Override protected void onPause(){super.onPause();if(mapView!=null)try{call(mapView,"onPause",new Class[0],new Object[0]);}catch(Throwable ignored){}}
    @Override protected void onResume(){super.onResume();if(mapView!=null)try{call(mapView,"onResume",new Class[0],new Object[0]);}catch(Throwable ignored){}}
    @Override protected void onDestroy(){destroyMap();super.onDestroy();}
    private TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
}
