package com.blinkmap.mod;

import android.app.Activity;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.content.res.ColorStateList;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Bundle;
import android.net.Uri;
import android.util.TypedValue;
import android.view.Gravity;
import android.view.View;
import android.view.WindowInsets;
import android.widget.CompoundButton;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Switch;
import android.widget.TextView;
import android.widget.Toast;

public final class ModSettingsActivity extends Activity {
    private static final String PREFS="blinkmod_settings";
    private static final String MAIN="main", UI="ui", MAP="map", PRIVACY="privacy", STEPS="steps", CHAT="chat", FRIENDS="friends", PROFILE="profile", USER="user", MISC="misc", NAVIGATE="navigate", CONFIG="config", LAB="lab", ABOUT="about";
    private static final int BASE_BG=Color.rgb(11,11,13), PRIMARY=Color.WHITE;
    private static final int SECONDARY=Color.rgb(148,148,156), DIVIDER=Color.rgb(46,46,51), PURPLE=Color.rgb(128,77,255);
    private String page=MAIN;

    @Override protected void onCreate(Bundle b){super.onCreate(b);setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);getWindow().setStatusBarColor(bg());getWindow().setNavigationBarColor(bg());render(MAIN);}
    @Override public void onBackPressed(){if(MAIN.equals(page))finish();else render(MAIN);}

    private void render(final String target){
        page=target;
        getWindow().setStatusBarColor(bg());getWindow().setNavigationBarColor(bg());
        final LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg());
        final FrameLayout head=header(target);root.addView(head,new LinearLayout.LayoutParams(-1,-2));
        ScrollView scroll=new ScrollView(this);scroll.setClipToPadding(false);
        LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);int side=compact()?dp(14):dp(20);body.setPadding(side,dp(6),side,dp(42));
        if(MAIN.equals(target))main(body); else if(UI.equals(target))ui(body); else if(MAP.equals(target))map(body); else if(PRIVACY.equals(target))privacy(body); else if(STEPS.equals(target))steps(body); else if(CHAT.equals(target))chat(body); else if(FRIENDS.equals(target))friends(body); else if(PROFILE.equals(target))profile(body); else if(USER.equals(target))userLookup(body); else if(MISC.equals(target))misc(body); else if(NAVIGATE.equals(target))navigate(body); else if(CONFIG.equals(target))config(body); else if(LAB.equals(target))lab(body); else about(body);
        scroll.addView(body,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        root.setOnApplyWindowInsetsListener(new View.OnApplyWindowInsetsListener(){@Override public WindowInsets onApplyWindowInsets(View v,WindowInsets i){int top=Build.VERSION.SDK_INT>=30?i.getInsets(WindowInsets.Type.statusBars()).top:i.getSystemWindowInsetTop();head.setPadding(dp(20),top+dp(8),dp(20),0);return i;}});
        setContentView(root);if(getSharedPreferences(PREFS,0).getBoolean("animations",true)){root.setAlpha(.75f);root.setTranslationX(dp(MAIN.equals(target)?-10:14));root.animate().alpha(1).translationX(0).setDuration(170).start();}
    }

    private FrameLayout header(String p){
        FrameLayout bar=new FrameLayout(this);bar.setPadding(dp(20),dp(8),dp(20),0);
        TextView title=text(title(p),MAIN.equals(p)?34:29,PRIMARY);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setGravity(Gravity.CENTER_VERTICAL);
        FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(-1,dp(64));tp.rightMargin=dp(62);bar.addView(title,tp);
        TextView action=text(MAIN.equals(p)?"×":"‹",MAIN.equals(p)?34:42,Color.rgb(177,177,184));action.setGravity(Gravity.CENTER);action.setBackground(round(Color.rgb(29,29,33),18));ripple(action);
        action.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){if(MAIN.equals(page))finish();else render(MAIN);}});
        FrameLayout.LayoutParams ap=new FrameLayout.LayoutParams(dp(48),dp(48));ap.gravity=Gravity.END|Gravity.CENTER_VERTICAL;bar.addView(action,ap);return bar;
    }

    private void main(LinearLayout b){
        LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);brand.setPadding(dp(4),dp(8),0,dp(22));brand.addView(appIcon(),new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout bn=labels("BlinkMod","версия 1.0");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(52),1);bp.leftMargin=dp(15);brand.addView(bn,bp);b.addView(brand);
        section(b,"ВОЗМОЖНОСТИ");LinearLayout features=group();features.addView(nav("Шаги","Быстрое действие и синхронизация",Icon.STEPS,STEPS));features.addView(line());features.addView(nav("Приватность","Геолокация и заряд батареи",Icon.SHIELD,PRIVACY));features.addView(line());features.addView(nav("Прочее","Чаты, друзья и профили",Icon.MISC,MISC));b.addView(features,bottom(22));
        section(b,"ОФОРМЛЕНИЕ");LinearLayout look=group();look.addView(nav("Интерфейс","Тема и кнопка BlinkMod",Icon.UI,UI));b.addView(look,bottom(22));
        section(b,"ИНСТРУМЕНТЫ");LinearLayout tools=group();tools.addView(nav("Blink Lab","Проверка API и журнал",Icon.LAB,LAB));tools.addView(line());tools.addView(nav("Навигация по ID","Открыть профиль, чат или маркер",Icon.NAVIGATE,NAVIGATE));tools.addView(line());tools.addView(nav("Конфигурация","Экспорт и восстановление настроек",Icon.CONFIG,CONFIG));tools.addView(line());tools.addView(nav("О BlinkMod","Версия и канал проекта",Icon.INFO,ABOUT));b.addView(tools,bottom(20));
    }

    private ImageView appIcon(){ImageView v=new ImageView(this);try{v.setImageDrawable(getPackageManager().getApplicationIcon(getPackageName()));}catch(Exception ignored){}v.setScaleType(ImageView.ScaleType.FIT_CENTER);return v;}

    private void misc(LinearLayout b){section(b,"ПРОЧИЕ ИНСТРУМЕНТЫ");LinearLayout g=group();g.addView(nav("Чаты","Поиск, непрочитанные и chat ID",Icon.CHAT,CHAT));g.addView(line());g.addView(nav("Друзья","Топ друзей и account ID",Icon.FRIENDS,FRIENDS));g.addView(line());g.addView(nav("Мой профиль","Данные и статистика аккаунта",Icon.PROFILE,PROFILE));g.addView(line());g.addView(nav("Поиск пользователя","Профиль и статистика по username",Icon.USER,USER));b.addView(g,bottom(16));note(b,"Экспериментальные инструменты собраны отдельно и не мешают основным функциям мода.");}
    private void ui(LinearLayout b){int tab=getSharedPreferences(PREFS,0).getInt("ui_tab",0);b.addView(tabs("Внешний вид","Кнопка","ui_tab",UI),bottom(22));if(tab==0){section(b,"ТЕМА И ПЛОТНОСТЬ");LinearLayout g=group();g.addView(toggle("AMOLED-режим","Чистый чёрный фон","amoled",true));g.addView(line());g.addView(toggle("Компактный режим","Меньше отступов и строки","compact",false));g.addView(line());g.addView(toggle("Анимации","Плавные переходы экранов","animations",true));b.addView(g,bottom(20));}else{section(b,"КНОПКА BLINKMOD");LinearLayout f=group();f.addView(toggle("Кнопка слева","Иначе остаётся справа","floating_left",false));f.addView(line());f.addView(choice("Размер","floating_size",new int[]{36,44,52},new String[]{"S","M","L"},44));f.addView(line());f.addView(choice("Прозрачность","floating_opacity",new int[]{60,80,90,100},new String[]{"60%","80%","90%","100%"},90));b.addView(f,bottom(16));note(b,"Кнопку можно перетаскивать по вертикали. Положение сохраняется.");}}
    private void map(LinearLayout b){section(b,"КАРТА");LinearLayout g=group();g.addView(status("чистая карта","скрытие игр и промо-кнопок","в работе"));g.addView(line());g.addView(status("компактные маркеры","меньше перекрытий на карте","скоро"));g.addView(line());g.addView(status("быстрый масштаб","сохранять выбранное приближение","скоро"));b.addView(g,bottom(20));}
    private void privacy(LinearLayout b){int tab=getSharedPreferences(PREFS,0).getInt("privacy_tab",0);b.addView(tabs("Геолокация","Батарея","privacy_tab",PRIVACY),bottom(22));if(tab==0){section(b,"ТОЧНОСТЬ ПОЗИЦИИ");LinearLayout q=group();q.addView(locationPrecision());q.addView(line());q.addView(value("Сейчас",StepHooks.locationPrecisionStatus()));q.addView(line());q.addView(value("Округлено за запуск",String.valueOf(StepHooks.locationPrecisionHits)));b.addView(q,bottom(16));note(b,"Координаты округляются непосредственно перед отправкой, GPS телефона не изменяется.");section(b,"ЧАСТОТА ОБНОВЛЕНИЙ");LinearLayout z=group();z.addView(geoFrequency());z.addView(line());z.addView(value("Текущий режим",StepHooks.geoIntervalStatus()));z.addView(line());z.addView(value("Пропущено за запуск",String.valueOf(StepHooks.geoRateLimitHits)));b.addView(z,bottom(16));note(b,"Позиция обновляется, но промежуточные запросы не отправляются.");section(b,"ПОЛНАЯ ПАУЗА");LinearLayout p=group();p.addView(value("Состояние",StepHooks.pauseStatus()));p.addView(line());p.addView(pauseDurations());p.addView(line());p.addView(resumeLocation());p.addView(line());p.addView(value("Заблокировано за запуск",String.valueOf(StepHooks.locationBlockHits)));b.addView(p,bottom(16));note(b,"Пауза полностью блокирует новые POST /api/geo/android.");}else{section(b,"ПЕРЕДАВАЕМЫЙ ЗАРЯД");LinearLayout g=group();g.addView(chargeMode());g.addView(line());g.addView(toggle("Не отправлять заряд","Передаёт charge как null","hide_charge",false));g.addView(line());g.addView(value("Подменено за запуск",String.valueOf(StepHooks.chargeFilterHits)));b.addView(g,bottom(16));note(b,"Скрытие имеет приоритет над выбранным фиксированным значением.");}}
    private void steps(LinearLayout b){int tab=getSharedPreferences(PREFS,0).getInt("steps_tab",0);b.addView(tabs("Быстро","Синхронизация","steps_tab",STEPS),bottom(22));if(tab==0){section(b,"БЫСТРОЕ ДЕЙСТВИЕ");b.addView(action100k(),bottom(16));note(b,"Запрос отправляется сразу и затем проверяется через API.");}else{section(b,"ШТАТНАЯ СИНХРОНИЗАЦИЯ");LinearLayout network=group();network.addView(toggle("Менять отправку","Правит шаги перед запросом Blink","network_steps_enabled",false));network.addView(line());network.addView(multiplier("Множитель отправки","network_steps_multiplier"));network.addView(line());network.addView(networkState());b.addView(network,bottom(16));note(b,"Применяется при следующей синхронизации. Максимум — 100 000 шагов.");}}
    private void lab(LinearLayout b){section(b,"ВНУТРЕННИЙ API");b.addView(apiCheck(),bottom(14));LinearLayout g=group();g.addView(value2("состояние",getSharedPreferences(PREFS,0).getString("api_steps_state","Проверок ещё не было")));b.addView(g,bottom(22));section(b,"ДИАГНОСТИКА");b.addView(copyDiagnostics(),bottom(20));section(b,"ЛОКАЛЬНЫЙ ЖУРНАЛ");String log=getSharedPreferences(PREFS,0).getString("lab_log","");TextView journal=text(log.length()==0?"Событий пока нет":log,14,log.length()==0?SECONDARY:PRIMARY);journal.setGravity(Gravity.START);journal.setTypeface(Typeface.MONOSPACE);journal.setPadding(dp(16),dp(14),dp(16),dp(16));journal.setBackground(round(Color.rgb(25,25,29),16));b.addView(journal,bottom(12));b.addView(clearJournal(),bottom(12));note(b,"В журнал не записываются токен, Authorization и содержимое профиля.");}
    private void chat(LinearLayout b){section(b,"ПОИСК ДИАЛОГОВ");b.addView(chatSearch(),bottom(14));LinearLayout state=group();state.addView(value("Состояние",getSharedPreferences(PREFS,0).getString("chat_state","Поиск ещё не запускался")));b.addView(state,bottom(22));section(b,"РЕЗУЛЬТАТЫ");String raw=getSharedPreferences(PREFS,0).getString("chat_results","");if(raw.length()==0){LinearLayout empty=group();empty.addView(value("Диалоги","Нет результатов"));b.addView(empty,bottom(16));}else{String[] rows=raw.split("\\n");LinearLayout results=group();for(int i=0;i<rows.length;i++){String[] parts=rows[i].split("\\t",-1);if(parts.length<3)continue;if(results.getChildCount()>0)results.addView(line());results.addView(chatRow(parts[0],parts[1],parts[2]));}b.addView(results,bottom(10));b.addView(copyBlock("Скопировать весь список",raw,"Список чатов скопирован"),bottom(16));}note(b,"Нажмите на строку для копирования chat ID, на стрелку — чтобы открыть чат.");}
    private void friends(LinearLayout b){section(b,"ДРУЗЬЯ");b.addView(friendsRefresh(),bottom(14));LinearLayout state=group();state.addView(value("Состояние",getSharedPreferences(PREFS,0).getString("friends_state","Список ещё не загружался")));b.addView(state,bottom(22));section(b,"ТОП ДРУЗЕЙ");String raw=getSharedPreferences(PREFS,0).getString("friends_results","");if(raw.length()==0){LinearLayout empty=group();empty.addView(value("Список","Нет данных"));b.addView(empty,bottom(16));}else{String[] rows=raw.split("\\n");LinearLayout results=group();for(int i=0;i<rows.length;i++){String[] parts=rows[i].split("\\t",-1);if(parts.length<3)continue;if(results.getChildCount()>0)results.addView(line());results.addView(friendRow(parts[0],parts[1],parts[2]));}b.addView(results,bottom(10));b.addView(copyBlock("Скопировать весь список",raw,"Список друзей скопирован"),bottom(16));}note(b,"Нажмите на строку для копирования account ID, на стрелку — чтобы открыть профиль.");}

    private void profile(LinearLayout b){section(b,"МОЙ АККАУНТ");b.addView(profileRefresh(),bottom(14));android.content.SharedPreferences p=getSharedPreferences(PREFS,0);LinearLayout state=group();state.addView(value("Состояние",p.getString("profile_state","Профиль ещё не загружался")));b.addView(state,bottom(22));section(b,"ДАННЫЕ ПРОФИЛЯ");LinearLayout info=group();info.addView(copyValue("Имя",p.getString("profile_name","—"),"Имя скопировано"));info.addView(line());String u=p.getString("profile_username","");info.addView(copyValue("Username",u.length()==0?"—":"@"+u,"Username скопирован"));info.addView(line());info.addView(copyValue("Account ID",p.getString("profile_account_id","—"),"Account ID скопирован"));b.addView(info,bottom(20));section(b,"СТАТИСТИКА");LinearLayout stats=group();stats.addView(value("Друзья",String.valueOf(p.getLong("profile_friends",0))));stats.addView(line());stats.addView(value("Просмотры профиля",String.valueOf(p.getLong("profile_views",0))));stats.addView(line());stats.addView(value("Звёзды",String.valueOf(p.getLong("profile_stars",0))));stats.addView(line());stats.addView(value("Чекины",String.valueOf(p.getLong("profile_checkins",0))));b.addView(stats,bottom(10));b.addView(copyProfileCard(false),bottom(16));note(b,"Строку можно нажать, чтобы скопировать значение.");}
    private void userLookup(LinearLayout b){section(b,"ПОИСК ПО USERNAME");b.addView(userSearch(),bottom(14));android.content.SharedPreferences p=getSharedPreferences(PREFS,0);LinearLayout state=group();state.addView(value("Поиск",p.getString("user_lookup_state","Ещё не запускался")));state.addView(line());state.addView(value("Доступность",p.getString("username_check_state","Ещё не проверялась")));b.addView(state,bottom(22));section(b,"ПРОФИЛЬ");LinearLayout info=group();info.addView(copyValue("Имя",emptyDash(p.getString("user_lookup_name","")),"Имя скопировано"));info.addView(line());String u=p.getString("user_lookup_username","");info.addView(copyValue("Username",u.length()==0?"—":"@"+u,"Username скопирован"));info.addView(line());info.addView(copyValue("Город",emptyDash(p.getString("user_lookup_city","")),"Город скопирован"));info.addView(line());info.addView(copyValue("Account ID",emptyDash(p.getString("user_lookup_id","")),"Account ID скопирован"));b.addView(info,bottom(12));String id=p.getString("user_lookup_id","");if(id.length()>0)b.addView(nativeOpen("Открыть профиль в Blink","blink:///profile/?id="+id),bottom(20));section(b,"ПУБЛИЧНАЯ СТАТИСТИКА");LinearLayout stats=group();stats.addView(value("Друзья",String.valueOf(p.getLong("user_lookup_friends",0))));stats.addView(line());stats.addView(value("Просмотры",String.valueOf(p.getLong("user_lookup_views",0))));stats.addView(line());stats.addView(value("Звёзды",String.valueOf(p.getLong("user_lookup_stars",0))));stats.addView(line());stats.addView(value("Чекины",String.valueOf(p.getLong("user_lookup_checkins",0))));b.addView(stats,bottom(10));b.addView(copyProfileCard(true),bottom(16));}
    private void navigate(LinearLayout b){section(b,"ВНУТРЕННИЙ ID");b.addView(navigationPanel(),bottom(16));note(b,"Открывает штатные экраны Blink через внутренние deep link. Поддерживаются числовые ID и UUID.");section(b,"ПОДДЕРЖИВАЕМЫЕ ЭКРАНЫ");LinearLayout g=group();g.addView(value("Профиль","account ID"));g.addView(line());g.addView(value("Чат","chat ID"));g.addView(line());g.addView(value("Маркер","marker ID"));b.addView(g,bottom(16));}
    private void config(LinearLayout b){section(b,"РЕЗЕРВНАЯ КОПИЯ");LinearLayout actions=group();actions.addView(configAction("Скопировать конфигурацию","Только настройки мода, без данных аккаунта",true));actions.addView(line());actions.addView(configAction("Восстановить из буфера","Применить ранее скопированную конфигурацию",false));actions.addView(line());actions.addView(clearInspectorData());b.addView(actions,bottom(16));note(b,"Экспорт не содержит токен, переписки, имена, ID или геолокацию.");section(b,"СОСТОЯНИЕ");LinearLayout state=group();state.addView(value("Последнее действие",getSharedPreferences(PREFS,0).getString("config_state","Резервных копий ещё не было")));b.addView(state,bottom(16));}
    private void about(LinearLayout b){ImageView icon=appIcon();LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(92),dp(92));ip.gravity=Gravity.CENTER_HORIZONTAL;ip.topMargin=dp(28);b.addView(icon,ip);TextView name=text("BlinkMod",30,PRIMARY);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);name.setGravity(Gravity.CENTER);name.setPadding(0,dp(14),0,0);b.addView(name);TextView version=text("версия 1.0",15,SECONDARY);version.setGravity(Gravity.CENTER);version.setPadding(0,dp(3),0,dp(34));b.addView(version);b.addView(channelButton(),bottom(16));TextView channel=text("обновления и новые сборки",13,SECONDARY);channel.setGravity(Gravity.CENTER);b.addView(channel);}

    private View nav(String a,String s,int icon,final String target){int h=compact()?58:70;LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(3),0,dp(3));Icon iv=new Icon(icon);r.addView(iv,new LinearLayout.LayoutParams(dp(58),dp(h)));LinearLayout labels=labels(a,s);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(h),1);lp.leftMargin=dp(compact()?4:10);r.addView(labels,lp);TextView arrow=text("›",31,SECONDARY);arrow.setGravity(Gravity.CENTER);r.addView(arrow,new LinearLayout.LayoutParams(dp(32),dp(h)));r.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){render(target);}});ripple(r);return r;}
    private View tabs(String left,String right,final String key,final String target){final LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(5),dp(5),dp(5),dp(5));bar.setBackground(round(Color.rgb(29,29,33),18));int selected=getSharedPreferences(PREFS,0).getInt(key,0);String[] names={left,right};for(int i=0;i<2;i++){final int value=i;TextView tab=text(names[i],15,selected==i?PRIMARY:SECONDARY);tab.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tab.setGravity(Gravity.CENTER);if(selected==i)tab.setBackground(round(PURPLE,14));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(46),1);if(i>0)lp.leftMargin=dp(5);bar.addView(tab,lp);tab.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){getSharedPreferences(PREFS,0).edit().putInt(key,value).apply();render(target);}});ripple(tab);}return bar;}
    private View toggle(String a,String s,final String key,boolean def){LinearLayout r=row();r.addView(labels(a,s),new LinearLayout.LayoutParams(0,dp(compact()?58:70),1));final Switch sw=new Switch(this);int[][] st={{android.R.attr.state_checked},{}};sw.setThumbTintList(new ColorStateList(st,new int[]{Color.WHITE,SECONDARY}));sw.setTrackTintList(new ColorStateList(st,new int[]{PURPLE,Color.rgb(64,64,68)}));sw.setChecked(getSharedPreferences(PREFS,0).getBoolean(key,def));sw.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener(){@Override public void onCheckedChanged(CompoundButton b,boolean c){getSharedPreferences(PREFS,0).edit().putBoolean(key,c).apply();if("hide_charge".equals(key))StepHooks.setHideCharge(c);if("pause_location".equals(key))StepHooks.setPauseLocation(c);if("amoled".equals(key)||"compact".equals(key))render(UI);}});r.addView(sw,new LinearLayout.LayoutParams(dp(64),dp(52)));r.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){sw.setChecked(!sw.isChecked());}});ripple(r);return r;}
    private View choice(String title,final String key,int[] values,String[] labels,int def){LinearLayout r=row();r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.START);TextView label=text(title,16,PRIMARY);label.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(label,new LinearLayout.LayoutParams(-1,dp(34)));LinearLayout choices=new LinearLayout(this);choices.setGravity(Gravity.CENTER_VERTICAL);int selected=getSharedPreferences(PREFS,0).getInt(key,def);for(int i=0;i<values.length;i++){final int value=values[i];final TextView x=text(labels[i],15,PRIMARY);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(round(selected==value?PURPLE:Color.rgb(47,47,51),13));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(42),1);if(i!=0)xp.leftMargin=dp(8);choices.addView(x,xp);x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){getSharedPreferences(PREFS,0).edit().putInt(key,value).apply();render(UI);}});}r.addView(choices,new LinearLayout.LayoutParams(-1,dp(42)));r.setPadding(dp(16),dp(12),dp(16),dp(14));return r;}
    private View status(String a,String s,String badge){LinearLayout r=row();r.addView(labels(a,s),new LinearLayout.LayoutParams(0,dp(70),1));TextView x=text(badge,13,SECONDARY);x.setGravity(Gravity.CENTER);x.setPadding(dp(11),0,dp(11),0);x.setBackground(round(Color.rgb(47,47,51),14));r.addView(x,new LinearLayout.LayoutParams(-2,dp(34)));return r;}
    private View value(String a,String b){LinearLayout r=row();TextView l=text(a,17,PRIMARY);l.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(l,new LinearLayout.LayoutParams(0,dp(62),1));TextView x=text(b,15,SECONDARY);x.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);r.addView(x,new LinearLayout.LayoutParams(-2,dp(62)));return r;}
    private View multiplier(String title,final String key){LinearLayout r=row();r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.START);TextView label=text(title,16,PRIMARY);label.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(label,new LinearLayout.LayoutParams(-1,dp(34)));LinearLayout choices=new LinearLayout(this);choices.setGravity(Gravity.CENTER_VERTICAL);final int[] values={1,2,5,10};for(final int n:values){final TextView x=text("×"+n,15,PRIMARY);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(round(getSharedPreferences(PREFS,0).getInt(key,2)==n?PURPLE:Color.rgb(47,47,51),13));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(42),1);if(n!=1)xp.leftMargin=dp(8);choices.addView(x,xp);x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){getSharedPreferences(PREFS,0).edit().putInt(key,n).apply();render(STEPS);}});}r.addView(choices,new LinearLayout.LayoutParams(-1,dp(42)));r.setPadding(dp(18),dp(14),dp(18),dp(16));return r;}
    private View networkState(){String sub=getSharedPreferences(PREFS,0).getString("api_steps_state","Запросов из BlinkMod ещё не было");return value2("последний запрос",sub);}
    private View action100k(){TextView x=text("Поставить 100 000 шагов",17,PRIMARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(62));x.setBackground(round(PURPLE,20));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(final View v){try{long now=System.currentTimeMillis();String iso=new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",java.util.Locale.US).format(new java.util.Date(now));StepHooks.onApiStarted();Class<?> c=Class.forName("com.blinkmap.mod.WorkBridge");c.getMethod("post100k",android.content.Context.class,Long.TYPE,String.class).invoke(null,getApplicationContext(),now,iso);Toast.makeText(ModSettingsActivity.this,"Запрос отправляется",Toast.LENGTH_SHORT).show();v.postDelayed(new Runnable(){@Override public void run(){render(STEPS);}},2200);v.postDelayed(new Runnable(){@Override public void run(){render(STEPS);}},5500);}catch(Throwable e){StepHooks.onApiError(e);Toast.makeText(ModSettingsActivity.this,"Не удалось отправить: "+e.getClass().getSimpleName(),Toast.LENGTH_LONG).show();render(STEPS);}}});ripple(x);return x;}
    private View apiCheck(){TextView x=text("Проверить подключение",17,PRIMARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(58));x.setBackground(round(PURPLE,18));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(final View v){try{StepHooks.onApiCheckStarted();Class<?> c=Class.forName("com.blinkmap.mod.WorkBridge");c.getMethod("verifyNow",android.content.Context.class).invoke(null,getApplicationContext());render(LAB);v.postDelayed(new Runnable(){@Override public void run(){render(LAB);}},1800);}catch(Throwable e){StepHooks.onApiVerifyError(e);render(LAB);}}});ripple(x);return x;}
    private View chatSearch(){LinearLayout box=group();box.setPadding(dp(14),dp(14),dp(14),dp(14));final EditText input=new EditText(this);input.setSingleLine(true);input.setHint("Название или имя");input.setHintTextColor(SECONDARY);input.setTextColor(PRIMARY);input.setTextSize(16);input.setText(getSharedPreferences(PREFS,0).getString("chat_query",""));input.setPadding(dp(14),0,dp(14),0);input.setBackground(round(Color.rgb(47,47,51),14));box.addView(input,new LinearLayout.LayoutParams(-1,dp(52)));TextView go=text("Найти чаты",16,PRIMARY);go.setTypeface(Typeface.DEFAULT,Typeface.BOLD);go.setGravity(Gravity.CENTER);go.setBackground(round(PURPLE,15));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(52));gp.topMargin=dp(10);box.addView(go,gp);go.setOnClickListener(new View.OnClickListener(){@Override public void onClick(final View v){String query=input.getText().toString().trim();StepHooks.onChatSearchStarted(query);try{Class<?> c=Class.forName("com.blinkmap.mod.WorkBridge");c.getMethod("searchChats",android.content.Context.class,String.class).invoke(null,getApplicationContext(),query);render(CHAT);v.postDelayed(new Runnable(){@Override public void run(){render(CHAT);}},1600);}catch(Throwable e){StepHooks.onChatSearchError(e);render(CHAT);}}});ripple(go);return box;}
    private View chatRow(String name,final String id,String unread){LinearLayout r=row();String title=name.length()==0?"Без названия":name;LinearLayout info=labels(title,"ID "+id);r.addView(info,new LinearLayout.LayoutParams(0,dp(70),1));TextView badge=text("0".equals(unread)?"":"+"+unread,14,PRIMARY);badge.setTypeface(Typeface.DEFAULT,Typeface.BOLD);badge.setGravity(Gravity.CENTER);if(badge.getText().length()>0)badge.setBackground(round(PURPLE,13));r.addView(badge,new LinearLayout.LayoutParams(dp(44),dp(34)));TextView open=text("↗",21,SECONDARY);open.setGravity(Gravity.CENTER);open.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){openBlink("blink:///chat/?chatId="+id);}});r.addView(open,new LinearLayout.LayoutParams(dp(38),dp(42)));r.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("Blink chat ID",id));Toast.makeText(ModSettingsActivity.this,"Chat ID скопирован",Toast.LENGTH_SHORT).show();}});ripple(r);return r;}
    private View navigationPanel(){LinearLayout box=group();box.setPadding(dp(14),dp(14),dp(14),dp(14));final EditText input=new EditText(this);input.setSingleLine(true);input.setHint("ID или UUID");input.setHintTextColor(SECONDARY);input.setTextColor(PRIMARY);input.setTextSize(16);input.setText(getSharedPreferences(PREFS,0).getString("nav_id",""));input.setPadding(dp(14),0,dp(14),0);input.setBackground(round(Color.rgb(47,47,51),14));box.addView(input,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout buttons=new LinearLayout(this);String[] labels={"Профиль","Чат","Маркер"};final String[] links={"blink:///profile/?id=","blink:///chat/?chatId=","blink:///map/marker/?id="};for(int i=0;i<labels.length;i++){final int n=i;TextView x=text(labels[i],14,PRIMARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setBackground(round(i==0?PURPLE:Color.rgb(47,47,51),13));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(46),1);if(i>0)lp.leftMargin=dp(7);buttons.addView(x,lp);x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){String id=input.getText().toString().trim();if(id.length()==0){Toast.makeText(ModSettingsActivity.this,"Введите ID",Toast.LENGTH_SHORT).show();return;}getSharedPreferences(PREFS,0).edit().putString("nav_id",id).apply();openBlink(links[n]+Uri.encode(id));}});ripple(x);}LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(46));bp.topMargin=dp(10);box.addView(buttons,bp);return box;}
    private View copyProfileCard(final boolean lookup){TextView x=text("Скопировать карточку профиля",15,SECONDARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(50));x.setBackground(round(Color.rgb(35,35,39),16));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){android.content.SharedPreferences p=getSharedPreferences(PREFS,0);String k=lookup?"user_lookup_":"profile_";String name=p.getString(k+"name","");String username=p.getString(k+"username","");String id=p.getString(k+(lookup?"id":"account_id"),"");StringBuilder card=new StringBuilder();if(name.length()>0)card.append(name).append('\n');if(username.length()>0)card.append('@').append(username).append('\n');card.append("account_id: ").append(id).append('\n').append("friends: ").append(p.getLong(k+"friends",0)).append(" | views: ").append(p.getLong(k+"views",0)).append(" | stars: ").append(p.getLong(k+"stars",0)).append(" | checkins: ").append(p.getLong(k+"checkins",0));if(id.length()>0)card.append('\n').append("blink:///profile/?id=").append(id);android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("Blink profile",card.toString()));Toast.makeText(ModSettingsActivity.this,"Карточка скопирована",Toast.LENGTH_SHORT).show();}});ripple(x);return x;}
    private View nativeOpen(String label,final String uri){TextView x=text(label,16,PRIMARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(54));x.setBackground(round(Color.rgb(35,35,39),16));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){openBlink(uri);}});ripple(x);return x;}
    private void openBlink(String uri){try{Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse(uri));i.setPackage(getPackageName());startActivity(i);}catch(Throwable e){Toast.makeText(this,"Не удалось открыть экран Blink",Toast.LENGTH_SHORT).show();}}
    private View userSearch(){LinearLayout box=group();box.setPadding(dp(14),dp(14),dp(14),dp(14));final EditText input=new EditText(this);input.setSingleLine(true);input.setHint("username");input.setHintTextColor(SECONDARY);input.setTextColor(PRIMARY);input.setTextSize(16);input.setText(getSharedPreferences(PREFS,0).getString("user_lookup_query",""));input.setPadding(dp(14),0,dp(14),0);input.setBackground(round(Color.rgb(47,47,51),14));box.addView(input,new LinearLayout.LayoutParams(-1,dp(52)));TextView go=text("Найти пользователя",16,PRIMARY);go.setTypeface(Typeface.DEFAULT,Typeface.BOLD);go.setGravity(Gravity.CENTER);go.setBackground(round(PURPLE,15));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(52));gp.topMargin=dp(10);box.addView(go,gp);go.setOnClickListener(new View.OnClickListener(){@Override public void onClick(final View v){String q=cleanUsername(input.getText().toString());if(q.length()==0){Toast.makeText(ModSettingsActivity.this,"Введите username",Toast.LENGTH_SHORT).show();return;}StepHooks.onUserLookupStarted(q);try{Class<?> c=Class.forName("com.blinkmap.mod.WorkBridge");c.getMethod("lookupUser",android.content.Context.class,String.class).invoke(null,getApplicationContext(),q);render(USER);v.postDelayed(new Runnable(){@Override public void run(){render(USER);}},1600);}catch(Throwable e){StepHooks.onUserLookupError(e);render(USER);}}});ripple(go);TextView check=text("Проверить доступность",15,PRIMARY);check.setTypeface(Typeface.DEFAULT,Typeface.BOLD);check.setGravity(Gravity.CENTER);check.setBackground(round(Color.rgb(47,47,51),15));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(48));cp.topMargin=dp(8);box.addView(check,cp);check.setOnClickListener(new View.OnClickListener(){@Override public void onClick(final View v){String q=cleanUsername(input.getText().toString());if(q.length()==0){Toast.makeText(ModSettingsActivity.this,"Введите username",Toast.LENGTH_SHORT).show();return;}StepHooks.onUsernameCheckStarted(q);try{Class<?> c=Class.forName("com.blinkmap.mod.WorkBridge");c.getMethod("checkUsername",android.content.Context.class,String.class).invoke(null,getApplicationContext(),q);render(USER);v.postDelayed(new Runnable(){@Override public void run(){render(USER);}},1400);}catch(Throwable e){StepHooks.onUsernameCheckError(e);render(USER);}}});ripple(check);return box;}
    private String cleanUsername(String raw){String q=raw==null?"":raw.trim();while(q.startsWith("@"))q=q.substring(1);return q;}
    private String emptyDash(String s){return s==null||s.length()==0?"—":s;}
    private View copyDiagnostics(){TextView x=text("Скопировать отчёт для поддержки",16,PRIMARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(56));x.setBackground(round(Color.rgb(35,35,39),16));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("BlinkMod diagnostics",diagnostics()));Toast.makeText(ModSettingsActivity.this,"Безопасный отчёт скопирован",Toast.LENGTH_SHORT).show();}});ripple(x);return x;}
    private String diagnostics(){android.content.SharedPreferences p=getSharedPreferences(PREFS,0);String version="?";try{version=getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(Throwable ignored){}return "BlinkMod 1.0\nAPK "+version+" | Android "+Build.VERSION.SDK_INT+"\nsteps="+p.getBoolean("network_steps_enabled",false)+" x"+p.getInt("network_steps_multiplier",2)+"\ncharge_hidden="+p.getBoolean("hide_charge",false)+" forced="+p.getInt("forced_charge",-1)+"\nlocation_pause="+StepHooks.pauseStatus()+" precision="+StepHooks.locationPrecisionStatus()+" interval="+StepHooks.geoIntervalStatus()+"\nchat="+p.getString("chat_state","not_run")+"\nfriends="+p.getString("friends_state","not_run")+"\nprofile="+p.getString("profile_state","not_run")+"\nhits: location="+StepHooks.locationBlockHits+", rate="+StepHooks.geoRateLimitHits+", precision="+StepHooks.locationPrecisionHits+", charge="+StepHooks.chargeFilterHits;}
    private View clearInspectorData(){LinearLayout r=row();r.addView(labels("Очистить данные инспекторов","Удалить сохранённые чаты, друзей и профиль"),new LinearLayout.LayoutParams(0,dp(70),1));TextView x=text("×",25,SECONDARY);x.setGravity(Gravity.CENTER);r.addView(x,new LinearLayout.LayoutParams(dp(42),dp(42)));r.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){getSharedPreferences(PREFS,0).edit().remove("chat_query").remove("chat_results").remove("chat_state").remove("friends_results").remove("friends_state").remove("profile_name").remove("profile_username").remove("profile_account_id").remove("profile_state").remove("profile_friends").remove("profile_views").remove("profile_stars").remove("profile_checkins").remove("user_lookup_query").remove("user_lookup_name").remove("user_lookup_username").remove("user_lookup_city").remove("user_lookup_id").remove("user_lookup_state").remove("user_lookup_friends").remove("user_lookup_views").remove("user_lookup_stars").remove("user_lookup_checkins").remove("username_check_state").putString("config_state","Данные инспекторов очищены").apply();Toast.makeText(ModSettingsActivity.this,"Сохранённые данные удалены",Toast.LENGTH_SHORT).show();render(CONFIG);}});ripple(r);return r;}
    private View configAction(String title,String sub,final boolean export){LinearLayout r=row();r.addView(labels(title,sub),new LinearLayout.LayoutParams(0,dp(70),1));TextView arrow=text(export?"↑":"↓",24,SECONDARY);arrow.setGravity(Gravity.CENTER);r.addView(arrow,new LinearLayout.LayoutParams(dp(42),dp(42)));r.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){if(export){String data=exportConfig();android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("BlinkMod config",data));getSharedPreferences(PREFS,0).edit().putString("config_state","Конфигурация скопирована").apply();Toast.makeText(ModSettingsActivity.this,"Конфигурация скопирована",Toast.LENGTH_SHORT).show();}else{try{android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);android.content.ClipData clip=cm.getPrimaryClip();String data=clip==null||clip.getItemCount()==0?"":String.valueOf(clip.getItemAt(0).coerceToText(ModSettingsActivity.this));if(importConfig(data)){StepHooks.init(getApplicationContext());Toast.makeText(ModSettingsActivity.this,"Настройки восстановлены",Toast.LENGTH_SHORT).show();}else Toast.makeText(ModSettingsActivity.this,"В буфере нет конфигурации BlinkMod",Toast.LENGTH_LONG).show();}catch(Throwable e){getSharedPreferences(PREFS,0).edit().putString("config_state","Ошибка импорта").apply();}}render(CONFIG);}});ripple(r);return r;}
    private String exportConfig(){android.content.SharedPreferences p=getSharedPreferences(PREFS,0);StringBuilder s=new StringBuilder("BLINKMOD_CONFIG_1\n");String[] bools={"amoled","compact","animations","floating_left","network_steps_enabled","hide_charge"};boolean[] defs={true,false,true,false,false,false};for(int i=0;i<bools.length;i++)s.append(bools[i]).append('=').append(p.getBoolean(bools[i],defs[i])?'1':'0').append('\n');String[] ints={"floating_size","floating_opacity","network_steps_multiplier","forced_charge","geo_interval_minutes","location_precision"};int[] idefs={44,90,2,-1,0,0};for(int i=0;i<ints.length;i++)s.append(ints[i]).append('=').append(p.getInt(ints[i],idefs[i])).append('\n');return s.toString();}
    private boolean importConfig(String data){if(data==null||!data.startsWith("BLINKMOD_CONFIG_1\n"))return false;android.content.SharedPreferences.Editor e=getSharedPreferences(PREFS,0).edit();String[] lines=data.split("\n");for(String line:lines){int at=line.indexOf('=');if(at<1)continue;String k=line.substring(0,at),v=line.substring(at+1);if("amoled".equals(k)||"compact".equals(k)||"animations".equals(k)||"floating_left".equals(k)||"network_steps_enabled".equals(k)||"hide_charge".equals(k))e.putBoolean(k,"1".equals(v));else try{int n=Integer.parseInt(v);if("floating_size".equals(k))e.putInt(k,Math.max(36,Math.min(52,n)));else if("floating_opacity".equals(k))e.putInt(k,Math.max(60,Math.min(100,n)));else if("network_steps_multiplier".equals(k))e.putInt(k,Math.max(1,Math.min(10,n)));else if("forced_charge".equals(k))e.putInt(k,Math.max(-1,Math.min(100,n)));else if("geo_interval_minutes".equals(k))e.putInt(k,n==5||n==15||n==30?n:0);else if("location_precision".equals(k))e.putInt(k,n==2||n==3?n:0);}catch(NumberFormatException ignored){}}e.putString("config_state","Конфигурация восстановлена").apply();return true;}

    private View profileRefresh(){TextView go=text("Обновить данные профиля",16,PRIMARY);go.setTypeface(Typeface.DEFAULT,Typeface.BOLD);go.setGravity(Gravity.CENTER);go.setMinimumHeight(dp(56));go.setBackground(round(PURPLE,16));go.setOnClickListener(new View.OnClickListener(){@Override public void onClick(final View v){StepHooks.onProfileStarted();try{Class<?> c=Class.forName("com.blinkmap.mod.WorkBridge");c.getMethod("loadMyProfile",android.content.Context.class).invoke(null,getApplicationContext());render(PROFILE);v.postDelayed(new Runnable(){@Override public void run(){render(PROFILE);}},1600);}catch(Throwable e){StepHooks.onProfileError(e);render(PROFILE);}}});ripple(go);return go;}
    private View copyValue(String label,final String data,final String toast){View r=value(label,data);r.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){if("—".equals(data))return;android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("BlinkMod",data));Toast.makeText(ModSettingsActivity.this,toast,Toast.LENGTH_SHORT).show();}});ripple(r);return r;}
    private View copyBlock(String label,final String data,final String toast){TextView x=text(label,15,SECONDARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(50));x.setBackground(round(Color.rgb(35,35,39),16));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("BlinkMod list",data));Toast.makeText(ModSettingsActivity.this,toast,Toast.LENGTH_SHORT).show();}});ripple(x);return x;}
    private View friendsRefresh(){TextView go=text("Обновить топ друзей",16,PRIMARY);go.setTypeface(Typeface.DEFAULT,Typeface.BOLD);go.setGravity(Gravity.CENTER);go.setMinimumHeight(dp(56));go.setBackground(round(PURPLE,16));go.setOnClickListener(new View.OnClickListener(){@Override public void onClick(final View v){StepHooks.onFriendsStarted();try{Class<?> c=Class.forName("com.blinkmap.mod.WorkBridge");c.getMethod("loadTopFriends",android.content.Context.class).invoke(null,getApplicationContext());render(FRIENDS);v.postDelayed(new Runnable(){@Override public void run(){render(FRIENDS);}},1600);}catch(Throwable e){StepHooks.onFriendsError(e);render(FRIENDS);}}});ripple(go);return go;}
    private View friendRow(String name,String username,final String id){LinearLayout r=row();String title=name.length()==0?(username.length()==0?"Без имени":username):name;String sub=(username.length()==0?"":"@"+username+" · ")+"ID "+id;LinearLayout info=labels(title,sub);r.addView(info,new LinearLayout.LayoutParams(0,dp(70),1));TextView copy=text("↗",22,SECONDARY);copy.setGravity(Gravity.CENTER);copy.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){openBlink("blink:///profile/?id="+id);}});r.addView(copy,new LinearLayout.LayoutParams(dp(42),dp(42)));r.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("Blink account ID",id));Toast.makeText(ModSettingsActivity.this,"Account ID скопирован",Toast.LENGTH_SHORT).show();}});ripple(r);return r;}
    private View clearJournal(){TextView x=text("Очистить журнал",15,SECONDARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(50));x.setBackground(round(Color.rgb(35,35,39),16));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){StepHooks.clearLog();render(LAB);}});ripple(x);return x;}
    private View pauseDurations(){LinearLayout r=row();r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.START);TextView label=text("приостановить на",16,PRIMARY);label.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(label,new LinearLayout.LayoutParams(-1,dp(34)));LinearLayout choices=new LinearLayout(this);choices.setGravity(Gravity.CENTER_VERTICAL);final long[] ms={15*60*1000L,60*60*1000L};String[] names={"15 минут","1 час"};for(int i=0;i<2;i++){final long duration=ms[i];TextView x=text(names[i],15,PRIMARY);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(round(Color.rgb(47,47,51),13));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(44),1);if(i>0)xp.leftMargin=dp(8);choices.addView(x,xp);x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){StepHooks.pauseFor(duration);render(PRIVACY);}});}TextView forever=text("∞",22,PRIMARY);forever.setGravity(Gravity.CENTER);forever.setTypeface(Typeface.DEFAULT,Typeface.BOLD);forever.setBackground(round(Color.rgb(47,47,51),13));LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(dp(66),dp(44));fp.leftMargin=dp(8);choices.addView(forever,fp);forever.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){StepHooks.setPauseLocation(true);render(PRIVACY);}});r.addView(choices,new LinearLayout.LayoutParams(-1,dp(44)));r.setPadding(dp(16),dp(12),dp(16),dp(14));return r;}
    private View resumeLocation(){TextView x=text("Возобновить отправку",15,PRIMARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(50));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){StepHooks.resumeLocation();render(PRIVACY);}});ripple(x);return x;}
    private View chargeMode(){LinearLayout r=row();r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.START);TextView label=text("показывать заряд",16,PRIMARY);label.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(label,new LinearLayout.LayoutParams(-1,dp(34)));LinearLayout choices=new LinearLayout(this);choices.setGravity(Gravity.CENTER_VERTICAL);final int[] values={-1,100,50,1};String[] names={"реальный","100","50","1"};for(int i=0;i<values.length;i++){final int value=values[i];TextView x=text(names[i],14,PRIMARY);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(round(StepHooks.forcedCharge==value&&!StepHooks.hideCharge?PURPLE:Color.rgb(47,47,51),13));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(42),1);if(i>0)xp.leftMargin=dp(7);choices.addView(x,xp);x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){StepHooks.setForcedCharge(value);render(PRIVACY);}});}r.addView(choices,new LinearLayout.LayoutParams(-1,dp(42)));r.setPadding(dp(16),dp(12),dp(16),dp(14));return r;}
    private View geoFrequency(){LinearLayout r=row();r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.START);TextView label=text("отправлять позицию",16,PRIMARY);label.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(label,new LinearLayout.LayoutParams(-1,dp(34)));LinearLayout choices=new LinearLayout(this);choices.setGravity(Gravity.CENTER_VERTICAL);final int[] values={0,5,15,30};String[] names={"всегда","5 мин","15 мин","30 мин"};int selected=getSharedPreferences(PREFS,0).getInt("geo_interval_minutes",0);for(int i=0;i<values.length;i++){final int value=values[i];TextView x=text(names[i],14,PRIMARY);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(round(selected==value?PURPLE:Color.rgb(47,47,51),13));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(42),1);if(i>0)xp.leftMargin=dp(7);choices.addView(x,xp);x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){StepHooks.setGeoIntervalMinutes(value);render(PRIVACY);}});}r.addView(choices,new LinearLayout.LayoutParams(-1,dp(42)));r.setPadding(dp(16),dp(12),dp(16),dp(14));return r;}
    private View locationPrecision(){LinearLayout r=row();r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.START);TextView label=text("передавать позицию",16,PRIMARY);label.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(label,new LinearLayout.LayoutParams(-1,dp(34)));LinearLayout choices=new LinearLayout(this);choices.setGravity(Gravity.CENTER_VERTICAL);final int[] values={0,3,2};String[] names={"точно","~100 м","~1 км"};int selected=getSharedPreferences(PREFS,0).getInt("location_precision",0);for(int i=0;i<values.length;i++){final int value=values[i];TextView x=text(names[i],14,PRIMARY);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(round(selected==value?PURPLE:Color.rgb(47,47,51),13));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(42),1);if(i>0)xp.leftMargin=dp(7);choices.addView(x,xp);x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){StepHooks.setLocationPrecision(value);render(PRIVACY);}});}r.addView(choices,new LinearLayout.LayoutParams(-1,dp(42)));r.setPadding(dp(16),dp(12),dp(16),dp(14));return r;}
    private View value2(String a,String b){LinearLayout r=row();r.addView(labels(a,b),new LinearLayout.LayoutParams(0,dp(70),1));TextView dot=text("●",13,PURPLE);dot.setGravity(Gravity.CENTER);r.addView(dot,new LinearLayout.LayoutParams(dp(32),dp(52)));return r;}
    private View channelButton(){TextView x=text("Открыть канал  @blinkmod",17,PRIMARY);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setMinimumHeight(dp(60));x.setBackground(round(PURPLE,19));x.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://t.me/blinkmod")));}catch(Throwable e){Toast.makeText(ModSettingsActivity.this,"Не удалось открыть ссылку",Toast.LENGTH_SHORT).show();}}});ripple(x);return x;}
    private LinearLayout labels(String a,String b){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER_VERTICAL);TextView t=text(a,18,PRIMARY);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(t);if(b!=null&&b.length()>0){TextView s=text(b,13,SECONDARY);s.setPadding(0,dp(1),0,0);x.addView(s);}return x;}
    private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(compact()?10:16),dp(compact()?2:5),dp(12),dp(compact()?2:5));r.setMinimumHeight(dp(compact()?60:72));return r;}
    private LinearLayout group(){LinearLayout g=new LinearLayout(this);g.setOrientation(LinearLayout.VERTICAL);g.setBackground(round(Color.rgb(24,24,28),18));g.setClipToOutline(true);return g;}
    private View line(){View v=new View(this);v.setBackgroundColor(DIVIDER);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(1));p.leftMargin=dp(18);v.setLayoutParams(p);return v;}
    private void section(LinearLayout b,String s){TextView t=text(s,12,SECONDARY);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setLetterSpacing(.08f);t.setPadding(dp(6),dp(2),0,dp(9));b.addView(t);}
    private void note(LinearLayout b,String s){TextView t=text(s,14,SECONDARY);t.setPadding(dp(16),0,dp(16),dp(12));b.addView(t);}
    private String title(String p){if(UI.equals(p))return"Интерфейс";if(MAP.equals(p))return"Карта";if(PRIVACY.equals(p))return"Приватность";if(STEPS.equals(p))return"Шаги";if(CHAT.equals(p))return"Чаты";if(FRIENDS.equals(p))return"Друзья";if(PROFILE.equals(p))return"Мой профиль";if(USER.equals(p))return"Поиск пользователя";if(MISC.equals(p))return"Прочее";if(NAVIGATE.equals(p))return"Навигация по ID";if(CONFIG.equals(p))return"Конфигурация";if(LAB.equals(p))return"Blink Lab";if(ABOUT.equals(p))return"О BlinkMod";return"Настройки";}
    private TextView text(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    private LinearLayout.LayoutParams bottom(int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(b);return p;}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private boolean compact(){return getSharedPreferences(PREFS,0).getBoolean("compact",false);}
    private int bg(){return getSharedPreferences(PREFS,0).getBoolean("amoled",true)?Color.BLACK:BASE_BG;}
    private void ripple(View v){TypedValue t=new TypedValue();if(getTheme().resolveAttribute(android.R.attr.selectableItemBackground,t,true))v.setForeground(getDrawable(t.resourceId));}

    private final class Icon extends View{
        static final int UI=0,MAP=1,SHIELD=2,STEPS=3,LAB=4,INFO=5,CHAT=6,FRIENDS=7,PROFILE=8,CONFIG=9,USER=10,NAVIGATE=11,MISC=12;final int type;final Paint p=new Paint(1);final Path q=new Path();Icon(int t){super(ModSettingsActivity.this);type=t;p.setColor(Color.WHITE);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2));p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeJoin(Paint.Join.ROUND);}
        @Override protected void onDraw(Canvas c){float x=getWidth()/2f,y=getHeight()/2f,s=Math.min(getWidth(),getHeight())*.28f;q.reset();if(type==UI){c.drawCircle(x,y,s,p);c.drawCircle(x,y,s*.35f,p);c.drawLine(x,y-s*1.35f,x,y-s,p);c.drawLine(x+s,y,x+s*1.35f,y,p);c.drawLine(x-s,y,x-s*1.35f,y,p);}else if(type==MAP){c.drawCircle(x,y,s,p);c.drawLine(x-s,y,x+s,y,p);c.drawOval(new RectF(x-s*.45f,y-s,x+s*.45f,y+s),p);}else if(type==SHIELD){q.moveTo(x,y-s);q.lineTo(x+s,y-s*.5f);q.lineTo(x+s*.75f,y+s*.55f);q.lineTo(x,y+s);q.lineTo(x-s*.75f,y+s*.55f);q.lineTo(x-s,y-s*.5f);q.close();c.drawPath(q,p);}else if(type==STEPS){c.drawOval(new RectF(x-s*.9f,y-s*.15f,x+s*.1f,y+s*.75f),p);c.drawOval(new RectF(x-s*.15f,y-s*.8f,x+s*.75f,y+s*.05f),p);}else if(type==CHAT){q.moveTo(x-s,y-s*.7f);q.lineTo(x+s,y-s*.7f);q.lineTo(x+s,y+s*.45f);q.lineTo(x+s*.25f,y+s*.45f);q.lineTo(x-s*.35f,y+s);q.lineTo(x-s*.2f,y+s*.45f);q.lineTo(x-s,y+s*.45f);q.close();c.drawPath(q,p);}else if(type==MISC){c.drawCircle(x-s*.65f,y,s*.13f,p);c.drawCircle(x,y,s*.13f,p);c.drawCircle(x+s*.65f,y,s*.13f,p);}else if(type==NAVIGATE){c.drawCircle(x-s*.3f,y-s*.3f,s*.55f,p);c.drawLine(x+s*.12f,y+s*.12f,x+s*.85f,y+s*.85f,p);c.drawLine(x-s*.3f,y-s*.68f,x-s*.3f,y-s*.05f,p);c.drawLine(x-s*.62f,y-s*.36f,x+s*.02f,y-s*.36f,p);}else if(type==USER){c.drawCircle(x-s*.2f,y-s*.42f,s*.34f,p);c.drawArc(new RectF(x-s*.85f,y,x+s*.45f,y+s),195,145,false,p);c.drawCircle(x+s*.5f,y+s*.35f,s*.33f,p);c.drawLine(x+s*.72f,y+s*.58f,x+s,y+s*.88f,p);}else if(type==CONFIG){c.drawRect(new RectF(x-s*.75f,y-s*.9f,x+s*.75f,y+s*.9f),p);c.drawLine(x-s*.45f,y-s*.35f,x+s*.45f,y-s*.35f,p);c.drawLine(x-s*.45f,y,x+s*.45f,y,p);c.drawLine(x-s*.45f,y+s*.35f,x+s*.15f,y+s*.35f,p);}else if(type==PROFILE){c.drawCircle(x,y-s*.48f,s*.36f,p);c.drawArc(new RectF(x-s,y-s*.02f,x+s,y+s),195,150,false,p);}else if(type==FRIENDS){c.drawCircle(x-s*.38f,y-s*.48f,s*.32f,p);c.drawCircle(x+s*.42f,y-s*.35f,s*.27f,p);c.drawArc(new RectF(x-s,y-s*.05f,x+s*.25f,y+s),195,150,false,p);c.drawArc(new RectF(x-s*.15f,y,x+s,y+s*.88f),200,135,false,p);}else if(type==LAB){q.moveTo(x-s*.35f,y-s);q.lineTo(x+s*.35f,y-s);q.moveTo(x-s*.15f,y-s);q.lineTo(x-s*.15f,y-s*.25f);q.lineTo(x-s*.75f,y+s*.75f);q.lineTo(x+s*.75f,y+s*.75f);q.lineTo(x+s*.15f,y-s*.25f);q.lineTo(x+s*.15f,y-s);c.drawPath(q,p);c.drawLine(x-s*.48f,y+s*.28f,x+s*.48f,y+s*.28f,p);}else{c.drawCircle(x,y,s,p);c.drawCircle(x,y-s*.4f,dp(2),p);c.drawLine(x,y-s*.05f,x,y+s*.55f,p);}}
    }
}
